INSERT INTO especie (nome, descricao) VALUES
('Seed Pokémon', 'Pokémon que possuem características de semente, geralmente sendo a forma inicial de evolução de um Pokémon.'),
('Lizard Pokémon', 'Pokémon que possuem características de lagarto, como escamas e habilidades relacionadas ao fogo.'),
('Flame Pokémon', 'Pokémon que possuem habilidades baseadas em chamas e fogo, podendo ter uma aparência de chama.'),
('Tiny Turtle Pokémon', 'Pequenos Pokémon que possuem características de tartaruga, como casco e habilidades relacionadas à água.'),
('Turtle Pokémon', 'Pokémon que evoluem a partir de Tiny Turtle Pokémon, possuindo um casco maior e mais habilidades relacionadas à água.'),
('Shellfish Pokémon', 'Pokémon que possuem características de crustáceos ou moluscos, como conchas e habilidades aquáticas.'),
('Worm Pokémon', 'Pokémon que possuem características de verme ou minhoca, com corpos alongados e habilidades diversas.'),
('Cocoon Pokémon', 'Pokémon que estão em estágio de casulo, se preparando para evoluir para uma forma mais poderosa.'),
('Butterfly Pokémon', 'Pokémon que evoluem a partir de Cocoon Pokémon, possuindo belas asas e habilidades relacionadas ao ar.'),
('Hairy Bug Pokémon', 'Pokémon insetos peludos com habilidades diversas, podendo se camuflar ou causar danos com seus pelos.'),
('Poison Bee Pokémon', 'Pokémon que possuem características de abelha venenosa, com habilidades de envenenamento e ataques com ferrões.'),
('Tiny Bird Pokémon', 'Pequenos Pokémon com características de pássaros, geralmente possuindo habilidades relacionadas ao voo.'),
('Bird Pokémon', 'Pokémon que evoluem a partir de Tiny Bird Pokémon, possuindo asas maiores e habilidades mais poderosas de voo e ataque.'),
('Mouse Pokémon', 'Pokémon com características de camundongos ou ratos, geralmente sendo ágeis e possuindo habilidades elétricas.'),
('Beak Pokémon', 'Pokémon que possuem um bico proeminente, podendo ser aves ou outros animais com habilidades relacionadas ao bico.'),
('Snake Pokémon', 'Pokémon que possuem características de serpente, com corpos alongados e habilidades de envenenamento.'),
('Cobra Pokémon', 'Pokémon que evoluem a partir de Snake Pokémon, possuindo corpos maiores e habilidades venenosas mais poderosas.'),
('Poison Pin Pokémon', 'Pokémon que possuem características de espinho ou agulha, geralmente com habilidades de envenenamento e ataques perfurantes.'),
('Drill Pokémon', 'Pokémon que possuem habilidades relacionadas a brocas e perfuração, podendo causar danos com seus ataques.'),
('Fairy Pokémon', 'Pokémon que possuem características mágicas e encantadoras, com habilidades de cura e ataques mágicos.'),
('Fox Pokémon', 'Pokémon com características inspiradas em raposas, sendo ágeis, astutos e possuindo habilidades únicas.');
